In [2]:
import numpy as np

In [3]:
x2d=np.array([[1,2,3],[2,5,7]])
print(x2d)
#shape and size
print(x2d.size)#total no.of elements
print(x2d.shape)#
print(x2d.ndim)#no. of dimensions

[[1 2 3]
 [2 5 7]]
6
(2, 3)
2


In [4]:
x25= np.random.randint(1,100,(5,5))
print(x25)

[[62 18  2 50 59]
 [45 16 96 82 12]
 [75 38 85 35 82]
 [92 19 83 67 43]
 [40  1 82  1 84]]


In [7]:
xseql = np.arange(1,101,4)#4 gives the gap and beween 1 to 101
print(xseql.size,"elements")
print("<=1D MATRIX")
print(xseql)
print(xseql.size)
print("<=1D MATRIX RESHAPED TO 2D MATRIX")
print(xseql.reshape(5,5))

25 elements
<=1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
<=1D MATRIX RESHAPED TO 2D MATRIX
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [9]:
xseq2 = np.arange(1,100,50)#4 gives the gap and beween 1 to 101
print(xseq2.size,"elements")
print("<=1D MATRIX")
print(xseq2)
print(xseql.size)
print("<=1D MATRIX RESHAPED TO 2D MATRIX")
print(xseql.reshape(10,5)) #returns matrix of (10,5)
print("<=1D MATRIX RESHAPED TO 3D MATRIX")
print(xseq2.reshape(5,5,2))

2 elements
<=1D MATRIX
[ 1 51]
25
<=1D MATRIX RESHAPED TO 2D MATRIX


ValueError: cannot reshape array of size 25 into shape (10,5)

In [ ]:
xseq2d= xseq2d.reshape(10,5)
print(xseq2d)

In [ ]:
np.ones((2,5)),dtype=int #it prints 1 in 2*5 matrix

indexing and slicing very important
boolean filter
maths and stats
methods

In [10]:

x25

array([[62, 18,  2, 50, 59],
       [45, 16, 96, 82, 12],
       [75, 38, 85, 35, 82],
       [92, 19, 83, 67, 43],
       [40,  1, 82,  1, 84]])

In [11]:
#IF YOU WANT IST ROW.
print(x25[0])

[62 18  2 50 59]


In [12]:
#for last row
print(x25[-1])

[40  1 82  1 84]


In [13]:
print(x25[0,1]) #for second element in 1st row

18


In [15]:
#1st column
print(x25[:,0])

[62 45 75 92 40]


In [16]:
#2nd column
print(x25[:,1])

[18 16 38 19  1]


In [17]:
#last c0lumn
print(x25[:,-1])

[59 12 82 43 84]


In [18]:
#column 0 and 1 index
print(x25[:,[0,1]])

[[62 18]
 [45 16]
 [75 38]
 [92 19]
 [40  1]]


In [19]:
#column 0,1,2 indexes
print(x25[:,[0,1,2]])
#same 
print(x25[:,3])

[[62 18  2]
 [45 16 96]
 [75 38 85]
 [92 19 83]
 [40  1 82]]
[50 82 35 67  1]


boolean


In [20]:
x25

array([[62, 18,  2, 50, 59],
       [45, 16, 96, 82, 12],
       [75, 38, 85, 35, 82],
       [92, 19, 83, 67, 43],
       [40,  1, 82,  1, 84]])

In [23]:
#filtering without numpy boolean filter(bada idea)
for i in x25:
    for j in i:
        if j<=20:
          print(j)

18
2
16
12
19
1
1


In [24]:
x25<=20 #boolean filter

array([[False,  True,  True, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False,  True, False]])

In [26]:
x25[x25<=20]

array([18,  2, 16, 12, 19,  1,  1])

In [28]:
x25[x25>50]

array([62, 59, 96, 82, 75, 85, 82, 92, 83, 67, 82, 84])

In [29]:
(x25>20) & (x25<70)

array([[ True, False, False,  True,  True],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False,  True,  True],
       [ True, False, False, False, False]])

In [30]:
x25[(x25>20) & (x25<70)]

array([62, 50, 59, 45, 38, 35, 67, 43, 40])

In [33]:
#for append in numpy
np.append(x25,[1,2,3,4,5]) # it just add the value after it and make it 1D matrix

array([62, 18,  2, 50, 59, 45, 16, 96, 82, 12, 75, 38, 85, 35, 82, 92, 19,
       83, 67, 43, 40,  1, 82,  1, 84,  1,  2,  3,  4,  5])

In [35]:
np.append(x25, np.array([[1,2,3,4,5]]),axis=0)#0in axis means row wise evaluatiom and 1 means column wise evaluation

array([[62, 18,  2, 50, 59],
       [45, 16, 96, 82, 12],
       [75, 38, 85, 35, 82],
       [92, 19, 83, 67, 43],
       [40,  1, 82,  1, 84],
       [ 1,  2,  3,  4,  5]])

In [36]:
np.append(x25, np.array([[1],[2],[3],[4],[5]]),axis=1) #for combing in column form write in different brackets.

array([[62, 18,  2, 50, 59,  1],
       [45, 16, 96, 82, 12,  2],
       [75, 38, 85, 35, 82,  3],
       [92, 19, 83, 67, 43,  4],
       [40,  1, 82,  1, 84,  5]])

In [48]:
#for matrix 2*3 and 3*2
a = np.random.randint(1,100,(3,2))
b= np.random.randint(1,100,(2,3))

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [41]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [42]:
a.T #IT STACKS AND TRANSPOSE THE MATRIX(a.transpose and a.T are same thing)

array([[65,  9,  1],
       [17, 92, 84]])

In [43]:
print(np.hstack((a,b.T))) #hstack means it stacks horizontally

[[65 17 77 48]
 [ 9 92 15 16]
 [ 1 84 94  7]]


In [45]:
print(np.hstack((a.T,b)))

[[65  9  1 77 15 94]
 [17 92 84 48 16  7]]


In [47]:
print(np.vstack((a,b.T)))#VSTACK IS VERTICAL STACK 
print(np.vstack((a.T,b)))

[[65 17]
 [ 9 92]
 [ 1 84]
 [77 48]
 [15 16]
 [94  7]]
[[65  9  1]
 [17 92 84]
 [77 15 94]
 [48 16  7]]


In [ ]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print()
print(y)


In [ ]:
print('add')
print(x+y)
print('sub')
print(x-y)
print('div')
print(x/y)
print('element wise multiplication')
print(x*y)
print('element wise mod')
print(x%y)

In [ ]:
print(x.min())#max value
